version: '3.5'


networks:

  redis_network:


services:

  data-science-funnels:
    build: .
    image: anomaly_app:latest
    container_name: app
    environment:
      - REDIS_HOST=redis
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - redis
    networks:
      - redis_network

  redis:
    image: redis:5.0.3-alpine3.8 
    container_name: redis
    networks:
      - redis_network
