---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: anomaly_app:latest
        imagePullPolicy: Never
        env:
          - name: REDIS_HOST
            value: "redis"
        resources:
          limits:
            memory: "512Mi"
            cpu: "400m"
          requests:
            memory: "512Mi"
            cpu: "200m"
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.3-alpine3.8
        imagePullPolicy: Always
