---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: anomaly-hpa
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: anomaly-deployment
  targetCPUUtilizationPercentage: 50
