---

apiVersion: v1
kind: Service
metadata:
  name: anomaly-service
  labels:
    app: anomaly
spec:
  type: NodePort
  ports:
  - name: anomaly-port
    nodePort: 30000
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: anomaly-funnels
